import { LanguageUrls } from "@/types";

export const languageUrls: LanguageUrls = {
  JavaScript: "/languages/javascript.png",
  TypeScript: "/languages/typescript.png",
  Python: "/languages/python.png",
  Java: "/languages/java.png",
  "C#": "/languages/csharp.png",
  "C++": "/languages/cpp.png",
  C: "/languages/c.png",
  Cuda: "/languages/cuda.png",
  Go: "/languages/go.png",
  Rust: "/languages/rust.png",
  Kotlin: "/languages/kotlin.png",
  Swift: "/languages/swift.png",
  PHP: "/languages/php.png",
  Ruby: "/languages/ruby.png",
  Dart: "/languages/dart.png",
  Elixir: "/languages/elixir.png",
  Haskell: "/languages/haskell.png",
  Lua: "/languages/lua.png",
  Scala: "/languages/scala.png",
  Clojure: "/languages/clojure.png",
  Erlang: "/languages/erlang.png",
  "F#": "/languages/fsharp.png",
  Julia: "/languages/julia.png",
  OCaml: "/languages/ocaml.png",
  R: "/languages/r.png",
  V: "/languages/v.png",
  Assembly: "/languages/assembly.png",
  D: "/languages/d.png",
  Perl: "/languages/perl.png",
  Racket: "/languages/racket.png",
  SQL: "/languages/sql.png",
  Agda: "/languages/agda.png",
  Back: "/languages/back.png",
  Ballerina: "/languages/ballerina.png",
  Haxe: "/languages/haxe.png",
  Lisp: "/languages/lisp.png",
  Jolie: "/languages/jolie.png",
  Nim: "/languages/nim.png",
  Pascal: "/languages/pascal.png",
  Odin: "/languages/odin.png",
  QSharp: "/languages/qsharp.png",
  Zig: "/languages/zig.png",
  Wolfram: "/languages/wolfram.png",
};
